In [ ]:
## Assignment: MySQL

### Q1. What is a database? Differentiate between SQL and NoSQL databases.

A **database** is a structured collection of data that allows for storage, retrieval, and management of information. Databases can be managed through Database Management Systems (DBMS).

**SQL (Structured Query Language) Databases**:
- **Schema-based**: SQL databases use structured schemas to define data and relationships.
- **Relational**: Data is stored in tables with predefined columns and rows.
- **Consistency**: Follow ACID (Atomicity, Consistency, Isolation, Durability) properties for transaction management.
- **Examples**: MySQL, PostgreSQL, Oracle Database.

**NoSQL (Not Only SQL) Databases**:
- **Schema-less**: NoSQL databases can store unstructured data without a fixed schema.
- **Non-relational**: Data can be stored as documents, key-value pairs, graphs, or wide-column stores.
- **Scalability**: Designed for horizontal scaling and large-scale data distribution.
- **Examples**: MongoDB, Cassandra, Redis.

### Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.

**DDL (Data Definition Language)** is a set of SQL commands used to define and manage database schema.

- **CREATE**: Used to create a new table or database.
  ```sql
  CREATE TABLE Students (
      StudentID INT PRIMARY KEY,
      Name VARCHAR(100),
      Age INT
  );
  ```
- **DROP**: Used to delete an existing table or database.
  ```sql
  DROP TABLE Students;
  ```
- **ALTER**: Used to modify an existing database object, such as a table.
  ```sql
  ALTER TABLE Students ADD COLUMN Address VARCHAR(255);
  ```
- **TRUNCATE**: Used to delete all records from a table without removing the table itself.
  ```sql
  TRUNCATE TABLE Students;
  ```

### Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.

**DML (Data Manipulation Language)** is a set of SQL commands used to manipulate data within tables.

- **INSERT**: Adds new records to a table.
  ```sql
  INSERT INTO Students (StudentID, Name, Age) VALUES (1, 'Alice', 23);
  ```
- **UPDATE**: Modifies existing records in a table.
  ```sql
  UPDATE Students SET Age = 24 WHERE StudentID = 1;
  ```
- **DELETE**: Removes records from a table.
  ```sql
  DELETE FROM Students WHERE StudentID = 1;
  ```

### Q4. What is DQL? Explain SELECT with an example.

**DQL (Data Query Language)** is used to query and retrieve data from a database.

- **SELECT**: Retrieves data from one or more tables.
  ```sql
  SELECT * FROM Students WHERE Age > 20;
  ```

### Q5. Explain Primary Key and Foreign Key.

- **Primary Key**: A unique identifier for a record in a table. Ensures that no two rows have the same primary key value.
  ```sql
  CREATE TABLE Students (
      StudentID INT PRIMARY KEY,
      Name VARCHAR(100)
  );
  ```

- **Foreign Key**: A field (or collection of fields) in one table that uniquely identifies a row in another table. Establishes a relationship between tables.
  ```sql
  CREATE TABLE Enrollments (
      EnrollmentID INT PRIMARY KEY,
      StudentID INT,
      CourseID INT,
      FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
  );
  ```

### Q6. Write a python code to connect MySQL to python. Explain the cursor() and execute() method.

```python
import mysql.connector

# Establishing connection
conn = mysql.connector.connect(
    host='localhost',
    user='your_username',
    password='your_password',
    database='your_database'
)

# Creating a cursor object
cursor = conn.cursor()

# Executing a query
cursor.execute("SELECT * FROM Students")

# Fetching results
results = cursor.fetchall()
for row in results:
    print(row)

# Closing the connection
cursor.close()
conn.close()
```

- **cursor()**: The cursor() method creates a cursor object which is used to execute SQL queries and fetch results.
- **execute()**: The execute() method executes the given SQL query using the cursor object.

### Q7. Give the order of execution of SQL clauses in an SQL query.

The order of execution of SQL clauses in an SQL query is:

1. **FROM**: Specifies the table to query data from.
2. **WHERE**: Filters rows based on a condition.
3. **GROUP BY**: Groups rows sharing a property.
4. **HAVING**: Filters groups based on a condition.
5. **SELECT**: Specifies which columns to retrieve.
6. **ORDER BY**: Orders the result set.
7. **LIMIT**: Limits the number of rows returned.

---